name: PourLiquid

task_name: PourLiquid

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [512, 7]
      type: point_cloud
    agent_pose:
      shape: [8]
      type: low_dim
  action:
    shape: [8]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.h5_dataset.H5Dataset
  dataset_path: outputs/collect/2025.05.07/17.44.09_Level3_PourLiquid/dataset
  horizon: ${horizon}
  n_obs_steps: ${n_obs_steps}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
