name: Level2_ShakeBeaker_infer

task_type: "shake"
controller_type: "infer_shakebeaker"

usd_path: "assets/chemistry_lab/general_lab/Scene1.usd"
obj_path: "/World/beaker"  
sub_obj_path: "/World/beaker/mesh"
show_video: True
save_video: True

max_episodes: 80

shake_model_path: "data/outputs/2025.04.07/21.52.51_train_diffusion_unet_image_real_image/checkpoints/epoch=0150-train_loss=0.000.ckpt"
shake_config_path: "data/outputs/2025.04.07/21.52.51_train_diffusion_unet_image_real_image/.hydra/config.yaml"

cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [2, 0, 2]
    resolution: [256, 256]
    focal_length: 5
    orientation: [0.61237, 0.35355, 0.35355, 0.61237]
    image_type: "rgb" 

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [0.1, 0, 2.5]
    resolution: [256, 256]
    focal_length: 5
    orientation: [0.70711, 0, 0, -0.70711]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: null  

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
