name: Level3_PourLiquid

task_type: "pickpour"
controller_type: "pickpour"

usd_path: "assets/chemistry_lab/pickpour_task/scene.usd"
target_path: "/World/beaker1"

mode: "collect"

infer:
  obs_names: {"camera_1_rgb": 'camera_1', "camera_2_rgb": 'camera_2'}
  policy_model_path: "outputs/train/2025.05.07/17.06.34_train_dp3_PourLiquid/checkpoints/epoch=0040-train_loss=0.001.ckpt"
  policy_config_path: "outputs/train/2025.05.07/17.06.34_train_dp3_PourLiquid/.hydra/config.yaml"
  normalizer_path: "outputs/train/2025.05.07/17.06.34_train_dp3_PourLiquid/checkpoints/normalize.ckpt"

task:
  max_steps: 1000
  obj_paths:
    - path: "/World/graduated_cylinder_03"
      position_range:
        x: [0.25, 0.35]
        y: [0.0, 0.1]
        z: [0.81, 0.81]
    - path: "/World/conical_bottle03"
      position_range:
        x: [0.25, 0.35]
        y: [0.0, 0.1]
        z: [0.81, 0.81]
    - path: "/World/beaker2"
      position_range:
        x: [0.25, 0.35]
        y: [0.0, 0.1]
        z: [0.84, 0.84]
        
  material_paths:
    - path: /World/table/surface
      materials:
        - "/World/Looks/Material1_plastic_dark_blue"
        - "/World/Looks/Material2_wood"
        - "/World/Looks/Material3_plastic_dark_green"
        - "/World/Looks/Material4_plastic_light_white"
        - "/World/Looks/Material5_black"

show_video: True
save_video: True
max_episodes: 100

cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [2, -0.1, 2]
    resolution: [256, 256]
    focal_length: 5
    orientation: [0.61237, 0.35355, 0.35355, 0.61237]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [0.1, -0.1, 3]
    resolution: [256, 256]
    focal_length: 5
    orientation: [0.70711, 0, 0, -0.70711]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: null 

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
