name: Level3_open_pointcloud

task_type: "open"
controller_type: "open"

usd_path: "assets/chemistry_lab/open_task/scene.usd"

mode: "collect"

show_video: True
save_video: True
max_episodes: 100

infer:
  obs_names: {"camera_1_semantic_pointcloud": 'point_cloud'}
  policy_model_path: "outputs/train/18.22.16_train_act_image_open_data/checkpoints/latest.ckpt"
  policy_config_path: "outputs/train/18.22.16_train_act_image_open_data/.hydra/config.yaml"
  normalizer_path: "outputs/train/18.22.16_train_act_image_open_data/checkpoints/normalize.ckpt"

task:
  max_steps: 1000
  obj_paths:
    - path: "/World/DryingBox_01"
      position_range:
        x: [0.72, 0.77]
        y: [0.0, 0.15]
        z: [0.78, 0.78]
    - path: "/World/DryingBox_02"
      position_range:
        x: [0.72, 0.77]
        y: [-0.05, 0.010]
        z: [0.78, 0.78]
    - path: "/World/MuffleFurnace"
      position_range:
        x: [0.65, 0.70]
        y: [-0.05, 0.010]
        z: [0.78, 0.78]
  material_paths:
    - path: "/World/table/surface"
      materials:
        - "/World/Looks/Material1_plastic_dark_blue"
        - "/World/Looks/Material2_wood"
        - "/World/Looks/Material3_plastic_dark_green"
        - "/World/Looks/Material4_plastic_light_white"
        - "/World/Looks/Material5_black"

cameras_names: ["camera_1", "camera_2"]
cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [-0.7, 1.4, 1.4]
    resolution: [256, 256]
    focal_length: 2
    orientation: [-0.2297, -0.18336, 0.59631, 0.74701]
    image_type: "semantic_pointcloud"
    class_to_prim: {
      "DryingBox_01": "/World/DryingBox_01",
      "DryingBox_02": "/World/DryingBox_02",
      "MuffleFurnace": "/World/MuffleFurnace",
      "franka": "/World/Franka"
    }

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: null

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
