name: level1_pick

task_type: "pick"
controller_type: "pick"

mode: "collect"
usd_path: "assets/chemistry_lab/pick_task/scene.usd"
show_video: True
save_video: True
max_episodes: 5

infer:
  obs_names: {"camera_1_rgb": 'camera_1', "camera_2_rgb": 'camera_2'}
  policy_model_path: "data/outputs/2025.03.25/12.43.59_train_act_image_pick_pick_data/checkpoints/latest.ckpt"
  policy_config_path: "data/outputs/2025.03.25/12.43.59_train_act_image_pick_pick_data/.hydra/config.yaml"
  normalizer_path: "data/outputs/2025.03.25/12.43.59_train_act_image_pick_pick_data/checkpoints/normalize.ckpt"

task:
  max_steps: 1000
  obj_paths:
    - path: "/World/conical_bottle02"
      position_range:
        x: [0.22, 0.32]
        y: [-0.05, 0.05]
        z: [0.80, 0.80]

cameras_names: ["camera_1", "camera_2"]
cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [2, 0, 2]
    resolution: [256, 256]
    focal_length: 6
    orientation: [0.61237, 0.35355, 0.35355, 0.61237]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [0.1, 0, 2.5]
    resolution: [256, 256]
    focal_length: 6
    orientation: [0.70711, 0, 0, -0.70711]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: null

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
