name: level1_open

task_type: "open"
controller_type: "open"

mode: "collect"
usd_path: "assets/chemistry_lab/open_task/scene.usd"
show_video: True
save_video: True
max_episodes: 100

infer:
  obs_names: {"camera_1_rgb": 'camera_1', "camera_2_rgb": 'camera_2'}
  policy_model_path: "outputs/train/18.22.16_train_act_image_open_data/checkpoints/latest.ckpt"
  policy_config_path: "outputs/train/18.22.16_train_act_image_open_data/.hydra/config.yaml"
  normalizer_path: "outputs/train/18.22.16_train_act_image_open_data/checkpoints/normalize.ckpt"

task:
  max_steps: 1000
  obj_paths:
    - path: "/World/DryingBox_01"
      position_range:
        x: [0.70, 0.80]
        y: [0.05, 0.15]
        z: [0.78, 0.78]
cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [-0.7, 1.4, 1.4]
    resolution: [256, 256]
    focal_length: 2
    orientation: [-0.2297, -0.18336, 0.59631, 0.74701]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [-1, -0.1, 3.6]
    resolution: [256, 256]
    focal_length: 4
    orientation: [0.69035, 0.15304, -0.15304, -0.69035]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: null

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}