name: Level1_pour

task_type: "pour"
controller_type: "pour"

usd_path: "assets/chemistry_lab/Scene1.usd"
target_path: "/World/beaker1"

mode: "collect"

task:
  max_steps: 2000
  obj_paths:
    - path: "/World/beaker"
      position_range:
        x: [0.22, 0.32]
        y: [0.13, 0.23]
        z: [0.77, 0.775]

    - path: "/World/target_beaker"
      position_range:
        x: [0.05, 0.15]
        y: [-0.25, -0.10]
        z: [0.77, 0.775]
        
show_video: True
save_video: True
max_episodes: 100


cameras_names: ["camera_1", "camera_2"]

cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [2, 0, 2]
    resolution: [256, 256]
    focal_length: 6
    orientation: [0.61237, 0.35355, 0.35355, 0.61237]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [0.1, 0, 3]
    resolution: [256, 256]
    focal_length: 5
    orientation: [0.70711, 0, 0, -0.70711]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]
l
collector:
  type: "default"
  compression: null  

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
